name: Intest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: oreolek/inform@latest

    steps:
      - uses: actions/checkout
      - name: Run Intest
        run: intest rinform all
