name: Intest

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on:
      group: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd tests && npm install
      - run: cd tests && npm run test
